export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LIST_BOOKS_REQUEST = "USER_LIST_BOOKS_REQUEST";
export const USER_LIST_BOOKS_SUCCESS = "USER_LIST_BOOKS_SUCCESS";
export const USER_LIST_BOOKS_FAIL = "USER_LIST_BOOKS_FAIL";
export const USER_LIST_BOOKS_RESET = "USER_LIST_BOOKS_RESET";

export const USER_ADD_BOOK_REQUEST = "USER_ADD_BOOK_REQUEST";
export const USER_ADD_BOOK_SUCCESS = "USER_ADD_BOOK_SUCCESS";
export const USER_ADD_BOOK_FAIL = "USER_ADD_BOOK_FAIL";
export const USER_ADD_BOOK_RESET = "USER_ADD_BOOK_RESET";

export const USER_REMOVE_BOOK_REQUEST = "USER_REMOVE_BOOK_REQUEST";
export const USER_REMOVE_BOOK_SUCCESS = "USER_REMOVE_BOOK_SUCCESS";
export const USER_REMOVE_BOOK_FAIL = "USER_REMOVE_BOOK_FAIL";
